//
//  HTMLReportTemplateTests.swift
//  LintStudioCoreTests
//
//  Tests for the HTML report template wrapper
//

@testable import LintStudioCore
import Testing

@MainActor
@Suite("HTMLReportTemplate Tests")
struct HTMLReportTemplateTests {
    @Test("Wraps body in valid HTML structure")
    func wrapsInHTML() {
        let result = HTMLReportTemplate.wrapInHTML(
            title: "Test Report",
            timestamp: "2026-01-01",
            body: "<p>Hello</p>"
        )

        #expect(result.contains("<!DOCTYPE html>"))
        #expect(result.contains("<title>Test Report</title>"))
        #expect(result.contains("<p>Hello</p>"))
        #expect(result.contains("Generated 2026-01-01"))
    }

    @Test("Escapes title in HTML output")
    func escapesTitle() {
        let result = HTMLReportTemplate.wrapInHTML(
            title: "Report <script>",
            timestamp: "now",
            body: ""
        )

        #expect(result.contains("Report &lt;script&gt;"))
        #expect(!result.contains("<script>"))
    }

    @Test("Uses custom footer text")
    func customFooter() {
        let result = HTMLReportTemplate.wrapInHTML(
            title: "Test",
            timestamp: "now",
            body: "",
            footerText: "Custom Footer"
        )

        #expect(result.contains("Custom Footer"))
    }

    @Test("Default footer is SwiftLint Rule Studio")
    func defaultFooter() {
        let result = HTMLReportTemplate.wrapInHTML(
            title: "Test",
            timestamp: "now",
            body: ""
        )

        #expect(result.contains("Generated by SwiftLint Rule Studio"))
    }

    @Test("Contains CSS styles")
    func containsStyles() {
        let result = HTMLReportTemplate.wrapInHTML(
            title: "Test",
            timestamp: "now",
            body: ""
        )

        #expect(result.contains("<style>"))
        #expect(result.contains("prefers-color-scheme: dark"))
    }
}
